# Generated by Django 4.1.7 on 2023-03-06 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('E', 'Electronics'), ('F', 'Fashion'), ('T', 'Toys'), ('H', 'Home'), ('S', 'Sport'), ('O', 'Other')], max_length=1)),
                ('start_bid', models.FloatField(max_length=4)),
                ('url_image', models.URLField(blank=True, max_length=202)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.list')),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=4)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.list')),
            ],
        ),
    ]
