# Generated by Django 4.1.7 on 2023-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_list_coments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='url_image',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
