# Generated by Django 4.1.7 on 2023-03-19 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_list_wonlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='wonlist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='won', to=settings.AUTH_USER_MODEL),
        ),
    ]
